[[main]]
  name = "Posts"
  url = ""
  weight = -110

#[[main]]
#  name = "Archives"
#  url = "post/rich-content/"
#  weight = -109

# Submenus are done this way: parent -> identifier
#[[main]]
#  name = "Links"
#  identifier = "Links"
#  weight = -108
#[[main]]
#  parent = "Links"
#  name = "X"
#  url = "https://X.com/Entroware"

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "twitter"
  weight = 1
  url = "https://X.com/Entroware"
[[social]]
  name = "github"
  type = "social"
  weight = 2
  url = "https://github.com/entroware/"

[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"
